var catechism = {
    joyful: {
        1: "CCC p. 484 - The Annunciation to Mary inaugurates “the fullness of time” (Gal. 4:4), the time of the fulfillment of God's promises and preparations. Mary was invited to conceive him in whom the “whole fullness of deity” would dwell “bodily” (Col. 2:9). The divine response to her question, “How can this be, since I know not man?”, was given by the power of the Spirit: “The Holy Spirit will come upon you” (Lk. 1:34-35 Gk. )",
        2: "CCC p. 717 - “There was a man sent from God, whose name was John” (Jn. 1:6). John was “filled with the Holy Spirit even from his mother's womb” (Lk. 1:15, 41) by Christ himself, whom the Virgin Mary had just conceived by the Holy Spirit. Mary's visitation to Elizabeth thus became a visit from God to his people (Lk. 1:68).",
        3: "CCC p. 525 - Jesus was born in a humble stable, into a poor family (Lk. 2:61). Simple shepherds were the first witnesses to this event. In this poverty heaven's glory was made manifest (Lk. 2:8-20). The Church never tires of singing the glory of this night: <br> <br>The Virgin today brings into the world the Eternal<br>And the earth offers a cave to the Inaccessible.<br>The angels and shepherds praise him<br>And the magi advance with the star,<br>For you are born for us,<br>Little Child, God eternal!<br>(Kontakion of Romanos the Melodist)",
        4: "CCC p. 527 - Jesus' circumcision, on the eighth day after his birth (Lk. 2:21), is the sign of his incorporation into Abraham's descendants, into the people of the covenant. It is the sign of his submission to the Law (Gal. 4:4) and his deputation to Israel's worship, in which he will participate throughout his life. This sign prefigures that “circumcision of Christ” which is Baptism (Col. 2:11-13).",
        5: "CCC p. 534 - The finding of Jesus in the temple is the only event that breaks the silence of the Gospels about the hidden years of Jesus (Lk. 2:41-52). Here Jesus lets us catch a glimpse of the mystery of his total consecration to a mission that flows from his divine sonship: “Did you not know that I must be about my Father's work?” (Lk. 2:49) Mary and Joseph did not understand these words, but they accepted them in faith. Mary “kept all these things in her heart” during the years Jesus remained hidden in the silence of an ordinary life."
    },
    sorrowful: {
        1: "CCC p. 612 - The cup of the New Covenant, which Jesus anticipated when he offered himself at the Last Supper, is afterwards accepted by him from his Father's hands in his agony in the garden at Gethsemani (Cf. Mt. 26:42; Lk. 22:20), making himself “obedient unto death”. Jesus prays: “My Father, if it be possible, let this cup pass from me” (Phil. 2:8; Mt. 26:39; Cf. Heb. 5:7-8). Thus he expresses the horror that death represented for his human nature. Like ours, his human nature is destined for eternal life; but unlike ours, it is perfectly exempt from sin, the cause of death (Cf. Rom. 5:12; Heb. 4:15). Above all, his human nature has been assumed by the divine person of the “Author of life”, the “Living One” (Cf. Acts. 3:15; Rev. 1:17; Jn. 1:4; 5:26). By accepting in his human will that the Father's will be done, he accepts his death as redemptive, for “he himself bore our sins in his body on the tree” (1 Pet. 224; Cf. Mt. 26:42).",
        2: "CCC p. 572 - The Church remains faithful to the interpretation of “all the Scriptures” that Jesus gave both before and after his Passover: “Was it not necessary that the Christ should suffer these things and enter into his glory?” (Lk. 24:26-27, 44-45) Jesus' sufferings took their historical, concrete form from the fact that he was “rejected by the elders and the chief priests and the scribes”, who handed “him to the Gentiles to be mocked and scourged and crucified” (Mk. 8:31; Mt. 20:19).",
        3: "CCC p. 615 - “For as by one man's disobedience many were made sinners, so by one man's obedience many will be made righteous” (Rom. 5:19). By his obedience unto death, Jesus accomplished the substitution of the suffering Servant, who “makes himself an offering for sin”, when “he bore the sin of many”, and who “shall make many to be accounted righteous”, for “he shall bear their iniquities” (Isa. 53:10-12). Jesus atoned for our faults and made satisfaction for our sins to the Father (Cf. Council of Trent 1547: DS 1529).",
        4: "CCC p. 618 - The cross is the unique sacrifice of Christ, the “one mediator between God and men” (1 Tim 2:5). But because in his incarnate divine person he has in some way united himself to every man, “the possibility of being made partners, in a way known to God, in the paschal mystery” is offered to all men (GS. 22 § 5; cf. § 2). He calls his disciples to “take up [their] cross and follow [him]” (Mt. 16:24), for “Christ also suffered for [us], leaving [us] an example so that [we] should follow in his steps.” (1 Pet. 2:21). In fact Jesus desires to associate with his redeeming sacrifice those who were to be its first beneficiaries (Cf. Mk 10:39; Jn. 21:18-19; Col. 1:24). This is achieved supremely in the case of his mother, who was associated more intimately than any other person in the mystery of his redemptive suffering (Cf. Lk. 2:35). Apart from the cross there is no other ladder by which we may get to heaven (St. Rose of Lima, cf. P. Hansen, Vita mirabilis Louvain, 1668).",
        5: "CCC p. 616 - It is love “to the end” (Jn. 13:1) that confers on Christ's sacrifice its value as redemption and reparation, as atonement and satisfaction. He knew and loved us all when he offered his life (Cf. Gal. 2:20; Eph. 5:2, 25). Now “the love of Christ controls us, because we are convinced that one has died for all; therefore all have died” (2 Cor. 5:14). No man, not even the holiest, was ever able to take on himself the sins of all men and offer himself as a sacrifice for all. The existence in Christ of the divine person of the Son, who at once surpasses and embraces all human persons, and constitutes himself as the Head of all mankind, makes possible his redemptive sacrifice for all."
    },
    glorious: {
        1: "CCC p. 651 - “If Christ has not been raised, then our preaching is in vain and your faith is in vain” (1 Cor. 15:14). The Resurrection above all constitutes the confirmation of all Christ's works and teachings. All truths, even those most inaccessible to human reason, find their justification if Christ by his Resurrection has given the definitive proof of his divine authority, which he had promised.",
        2: "CCC p. 661 - This final stage stays closely linked to the first, that is, to his descent from heaven in the Incarnation. Only the one who “came from the Father” can return to the Father: Christ Jesus (Cf. Jn. 16:28). “No one has ascended into heaven but he who descended from heaven, the Son of man” (Jn. 3:13; cf. Eph. 4:8-10). Left to its own natural powers humanity does not have access to the “Father's house”, to God's life and happiness (Jn. 14:2). Only Christ can open to man such access that we, his members, might have confidence that we too shall go where he, our Head and our Source, has preceded us. (Roman Missal, Preface of the Ascension: “sed ut illuc confideremus, sua membra, nos subsequi quo ipse, caput nostrum principiumque, praecessit.”)",
        3: "CCC p. 731 - On the day of Pentecost when the seven weeks of Easter had come to an end, Christ's Passover is fulfilled in the outpouring of the Holy Spirit, manifested, given, and communicated as a divine person: of his fullness, Christ, the Lord, pours out the Spirit in abundance (Cf. Acts 2:33-36).",
        4: "CCC p. 996 - “Finally the Immaculate Virgin, preserved free from all stain of original sin, when the course of her earthly life was finished, was taken up body and soul into heavenly glory, and exalted by the Lord as Queen over all things, so that she might be the more fully conformed to her Son, the Lord of lords and conqueror of sin and death” (LG 59; cf. Pius XII, Munificentissimus Deus 1950:DS 3903; cf. Rev 19:16). The Assumption of the Blessed Virgin is a singular participation in her Son's Resurrection and an anticipation of the resurrection of other Christians: In giving birth you kept your virginity; in your Dormition you did not leave the world, O Mother of God, but were joined to the source of Life. You conceived the living God and, by your prayers, will deliver our souls from death (Byzantine Liturgy, Troparion, Feast of the Dormition, August 15th).",
        5: "CCC p. 972 - After speaking of the Church, her origin, mission, and destiny, we can find no better way to conclude than by looking to Mary. In her we contemplate what the Church already is in her mystery on her own “pilgrimage of faith”, and what she will be in the homeland at the end of her journey. There, “in the glory of the Most Holy and Undivided Trinity”, “in the communion of all the saints” (LG 69), the Church is awaited by the one she venerates as Mother of her Lord and as her own mother. In the meantime the Mother of Jesus, in the glory which she possesses in body and soul in heaven, is the image and beginning of the Church as it is to be perfected in the world to come. Likewise she shines forth on earth until the day of the Lord shall come, a sign of certain hope and comfort to the pilgrim People of God (LG 68; Cf. 2 Pet 3 10)."
    }
}